### ISSUE TITLE
Ability to download po file even you are not the member

### ISSUE THREAD

**Issue by katzueno** [concrete5/translate.concretecms.org#32]
I have a project which we want to install some less than 80% language.
(it's better than nothing.)

I am not proficient to the language. But there are some occasion that I would like to have an access to po file.

I think there was PO download button certain point.
I would like PO download button back up.

Maybet to add "PO" icon in the list of languages

![image](https://user-images.githubusercontent.com/485751/163514517-35433aad-f1b2-464f-bfdd-03b3d293de58.png)

**Comment by mlocati** [comment]
> I have a project which we want to install some less than 80% language.

The minimum translation progress should be 60%, and it should be controlled by the [`concrete.i18n.community_translation.progress_limit` configuration key](https://github.com/concrete5/concrete5/blob/9.0.2/concrete/config/concrete.php#L945-L946).

In any case, I've added back that "download po" button.

**Comment by mlocati** [comment]
This issue can be closed
